---
- name: Configure GitLab and Jenkins
  hosts: localhost
  vars:
    gitlab_url: "http://gitlab.development.local"
    jenkins_url: "http://jenkins.development.local"
    jenkins_admin_password: "admin123"
    gitlab_admin_password: "admin123"
    
  tasks:
    - name: Wait for GitLab to be ready
      uri:
        url: "{{ gitlab_url }}/api/v4/version"
      register: result
      until: result.status == 200
      retries: 30
      delay: 10
      
    - name: Get GitLab root token
      uri:
        url: "{{ gitlab_url }}/oauth/token"
        method: POST
        body_format: json
        body:
          grant_type: password
          username: root
          password: "{{ gitlab_admin_password }}"
      register: gitlab_token
      
    - name: Create GitLab API token for Jenkins
      uri:
        url: "{{ gitlab_url }}/api/v4/users/1/personal_access_tokens"
        method: POST
        headers:
          Authorization: "Bearer {{ gitlab_token.json.access_token }}"
        body_format: json
        body:
          name: jenkins-token
          scopes:
            - api
            - read_repository
            - write_repository
          expires_at: "2025-12-31"
      register: gitlab_jenkins_token
      
    - name: Wait for Jenkins to be ready
      uri:
        url: "{{ jenkins_url }}/login"
      register: result
      until: result.status == 200
      retries: 30
      delay: 10
      
    - name: Get Jenkins crumb
      uri:
        url: "{{ jenkins_url }}/crumbIssuer/api/json"
        user: admin
        password: "{{ jenkins_admin_password }}"
        force_basic_auth: yes
      register: jenkins_crumb
      
    - name: Install Jenkins plugins
      uri:
        url: "{{ jenkins_url }}/pluginManager/installNecessaryPlugins"
        method: POST
        user: admin
        password: "{{ jenkins_admin_password }}"
        force_basic_auth: yes
        headers:
          Jenkins-Crumb: "{{ jenkins_crumb.json.crumb }}"
        body_format: xml
        body: |
          <jenkins>
            <install plugin="gitlab-plugin@1.7.16" />
            <install plugin="kubernetes@3900.va_dce992317b_4" />
            <install plugin="docker-workflow@572.v950f58993843" />
            <install plugin="pipeline-stage-view@2.34" />
            <install plugin="blueocean@1.27.9" />
          </jenkins>
